### PR TITLE
Force HTTP check under corresponding protocols

### LINKED ISSUE #55: Support for non-default HTTP ports
Hello,

I have some HTTP servers running on ports other than 80 and 443, which are hosted by docker containers.
Those containers are run on demand by users, and I would like to wait until they can handle HTTP requests before returning to user.
But sometimes the module fails to wait until server is ready.

I found in the module that ports other than 80 and 443 are checked simply by port existence, but not HTTP response.
I think it is "docker opening up the port before running the HTTP server" that cause the problem.

After a simple experiment of forced HTTP checking on non-standard ports, it works as expected.
Is it possible to support such scenario?

Thanks.

### PR DESCRIPTION
**Pull request by solarispika**
Fixes #55.

Since URL object with http or https protocol and default port(80 or 443)
will not show the port, the port is only assigned to default port 443
when the protocol is neither one of them.

### CODE REVIEW

**Comment by sindresorhus** [comment]
CI is failing

**Comment by solarispika** [comment]
The failed test tests `imap.gmail.com:995` which is prepended with `http://` before testing.
I see comment on `target` says: Protocols other than `http:` and `https:` are not supported.
I'm not sure if the test have its purpose or it can be removed?
Or maybe we can only force HTTP check when the target is explicitly using HTTP?

File: index.js [hunk 1]
```diff
@@ -38,10 +38,11 @@ const checkHttp = async (url, timeout) => {
 const getAddress = async hostname => net.isIP(hostname) ? hostname : (await dnsLookupP(hostname)).address;
 
 const isTargetReachable = timeout => async target => {
+	const isHTTP = ['http:', 'https:'].some(prot => target.indexOf(prot) === 0);
```
Comment (sindresorhus) [inline index.js:41]: This is overly complicated.

```suggestion
	const isHTTP = target.startsWith('https://') || target.startsWith('http://');
```

**Comment by sindresorhus** [comment]
> Or maybe we can only force HTTP check when the target is explicitly using HTTP?

Isn't that what we are already doing now?

**Comment by sindresorhus** [comment]
> I'm not sure if the test have its purpose or it can be removed?

I would recommend "git blaming" it and check why it was added.

**Comment by solarispika** [comment]
#38 removed support for other well-known protocol, so it changed the test of ftp url to the current one.
The words "Protocols other than http: and https: are not supported." does not limit the use of other ports.
I think it is fine to leave the test now.
